name: user_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  easy_localization: ^3.0.1

  cupertino_icons: ^1.0.2
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6

  carousel_slider: ^5.0.0
  image_picker: ^1.2.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  shared_preferences: ^2.2.3
  flutter_staggered_grid_view: ^0.4.1
  number_inc_dec: ^0.8.0
  fluttertoast: ^9.0.0
  provider: ^6.1.2
  url_launcher: ^6.1.10
  timezone: ^0.11.0
  flutter_stripe: ^12.2.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  # assets:
    # - ../assets/images/
    # - ../assets/images/slider/
    # - assets/translations/

  fonts:
    - family: Acme
      fonts:
        - asset: ../assets/fonts/Acme-Regular.ttf
    - family: Kiwi
      fonts:
        - asset: ../assets/fonts/KiwiMaru-Medium.ttf
    - family: Signatra
      fonts:
        - asset: ../assets/fonts/Signatra.ttf
    - family: Train
      fonts:
        - asset: ../assets/fonts/TrainOne-Regular.ttf
